### PR TITLE
fix(bug): don't export properties that are separately provide'd

### LINKED ISSUE #52: Duplicate declarations
```
goog.provide("goog.fx.dom");
goog.provide("goog.fx.dom.ColorTransform");

/** @type {number} */
goog.fx.dom.a = 1;

/** @constructor */
goog.fx.dom.ColorTransform = function() {}
```

we visit the ColorTransform symbol twice: once for the first provide (which is non-default so we traverse all the symbols) and again for the second provide, where it is the default.

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #52

### CODE REVIEW

**Comment by rkirov** [comment]
No usage file, or forgot to add? I think it would be useful to verify that importing `goog:goog.one` and `goog:goog.one.Two` is safe.

**Comment by rkirov** [comment]
LGTM, just add usage file

**Comment by alexeagle** [comment]
I tested this with google3 and there is still a problem with duplicates produced. trying to reproduce in this test case...

**Comment by alexeagle** [comment]
I'll open a separate bug for the other duplication, it seems to be a different cause.

**Comment by alexeagle** [comment]
merged in 4ddddad

**Pull request closed without merging**
